### ISSUE TITLE
Data validation error while setting up test fixtures

### ISSUE THREAD

**Issue by jmiranda** [openboxes/openboxes#1803]
Expected Behaviors
- Creating test fixtures should be disabled by default
- Creating test fixtures should not cause a validation error

Stacktrace
```2020-07-21 14:33:35,404 [main] INFO  bootstrap.BootStrap  - Finished running liquibase changelog(s)!
2020-07-21 14:33:35,405 [main] INFO  bootstrap.BootStrap  - Insert test fixtures?  true
2020-07-21 14:33:35,405 [main] INFO  bootstrap.BootStrap  - Inserting test fixtures ...
2020-07-21 14:33:35,406 [main] INFO  bootstrap.BootStrap  - Setup test fixture...
2020-07-21 14:33:36,727 [main] ERROR context.GrailsContextLoader  - Error executing bootstraps: Validation Error(s) occurred during save():
- Field error in object 'org.pih.warehouse.core.Location' on field 'organization': rejected value [null]; codes [org.pih.warehouse.core.Location.organization.validator.error.org.pih.warehouse.core.Location.organization,org.pih.warehouse.core.Location.organization.validator.error.organization,org.pih.warehouse.core.Location.organization.validator.error.org.pih.warehouse.core.Organization,org.pih.warehouse.core.Location.organization.validator.error,location.organization.validator.error.org.pih.warehouse.core.Location.organization,location.organization.validator.error.organization,location.organization.validator.error.org.pih.warehouse.core.Organization,location.organization.validator.error,org.pih.warehouse.core.Location.organization.validator.required.org.pih.warehouse.core.Location.organization,org.pih.warehouse.core.Location.organization.validator.required.organization,org.pih.warehouse.core.Location.organization.validator.required.org.pih.warehouse.core.Organization,org.pih.warehouse.core.Location.organization.validator.required,location.organization.validator.required.org.pih.warehouse.core.Location.organization,location.organization.validator.required.organization,location.organization.validator.required.org.pih.warehouse.core.Organization,location.organization.validator.required,validator.required.org.pih.warehouse.core.Location.organization,validator.required.organization,validator.required.org.pih.warehouse.core.Organization,validator.required]; arguments [organization,Location,null,[DEPOT, SUPPLIER]]; default message [Property [{0}] of class [{1}] with value [{2}] does not pass custom validation]

grails.validation.ValidationException: Validation Error(s) occurred during save():
- Field error in object 'org.pih.warehouse.core.Location' on field 'organization': rejected value [null]; codes [org.pih.warehouse.core.Location.organization.validator.error.org.pih.warehouse.core.Location.organization,org.pih.warehouse.core.Location.organization.validator.error.organization,org.pih.warehouse.core.Location.organization.validator.error.org.pih.warehouse.core.Organization,org.pih.warehouse.core.Location.organization.validator.error,location.organization.validator.error.org.pih.warehouse.core.Location.organization,location.organization.validator.error.organization,location.organization.validator.error.org.pih.warehouse.core.Organization,location.organization.validator.error,org.pih.warehouse.core.Location.organization.validator.required.org.pih.warehouse.core.Location.organization,org.pih.warehouse.core.Location.organization.validator.required.organization,org.pih.warehouse.core.Location.organization.validator.required.org.pih.warehouse.core.Organization,org.pih.warehouse.core.Location.organization.validator.required,location.organization.validator.required.org.pih.warehouse.core.Location.organization,location.organization.validator.required.organization,location.organization.validator.required.org.pih.warehouse.core.Organization,location.organization.validator.required,validator.required.org.pih.warehouse.core.Location.organization,validator.required.organization,validator.required.org.pih.warehouse.core.Organization,validator.required]; arguments [organization,Location,null,[DEPOT, SUPPLIER]]; default message [Property [{0}] of class [{1}] with value [{2}] does not pass custom validation]

	at BootStrap.createSupplierLocation(BootStrap.groovy:538)
	at BootStrap$createSupplierLocation.callCurrent(Unknown Source)
	at BootStrap.insertTestFixture(BootStrap.groovy:491)
	at BootStrap$_closure1.doCall(BootStrap.groovy:460)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:251)
	at grails.util.Environment.executeForEnvironment(Environment.java:244)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:220)
	at org.grails.tomcat.InlineExplodedTomcatServer.doStart(InlineExplodedTomcatServer.groovy:112)
	at org.grails.tomcat.InlineExplodedTomcatServer$doStart.callCurrent(Unknown Source)
	at org.grails.tomcat.TomcatServer.start(TomcatServer.groovy:97)
	at grails.web.container.EmbeddableServer$start.call(Unknown Source)
	at _GrailsRun_groovy$_run_closure5_closure12.doCall(_GrailsRun_groovy:158)
	at _GrailsRun_groovy$_run_closure5_closure12.doCall(_GrailsRun_groovy)
	at _GrailsSettings_groovy$_run_closure10.doCall(_GrailsSettings_groovy:280)
	at _GrailsSettings_groovy$_run_closure10.call(_GrailsSettings_groovy)
	at _GrailsRun_groovy$_run_closure5.doCall(_GrailsRun_groovy:149)
	at _GrailsRun_groovy$_run_closure5.call(_GrailsRun_groovy)
	at _GrailsRun_groovy.runInline(_GrailsRun_groovy:116)
	at _GrailsRun_groovy.this$4$runInline(_GrailsRun_groovy)
	at _GrailsRun_groovy$_run_closure1.doCall(_GrailsRun_groovy:59)
	at RunApp$_run_closure1.doCall(RunApp.groovy:33)
	at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)
	at gant.Gant.withBuildListeners(Gant.groovy:427)
	at gant.Gant.this$2$withBuildListeners(Gant.groovy)
	at gant.Gant$this$2$withBuildListeners.callCurrent(Unknown Source)
	at gant.Gant.dispatch(Gant.groovy:415)
	at gant.Gant.this$2$dispatch(Gant.groovy)
	at gant.Gant.invokeMethod(Gant.groovy)
	at gant.Gant.executeTargets(Gant.groovy:590)
	at gant.Gant.executeTargets(Gant.groovy:589)
Application context shutting down...
```

**Comment by jmiranda** [comment]
Duplicate of #2124
