### ISSUE TITLE
Cannot rollback issued requisition due to Hibernate flush bug

### ISSUE THREAD

**Issue by jmiranda** [openboxes/openboxes#187]
> From: Kelsey Nagel <knagel@pih.org>
> Date: Wed, Mar 29, 2017 at 11:05 AM
> Subject: Error trying to rollback a requisition
> To: Justin Miranda <justin@openboxes.com>
>
>Hi Justin,
>
> I am getting the below error when I try to rollback a requisition that has been issued. Can you let me know what you think? The requisition I am trying to do this on is 367MBU in the QA server. Here is the error:
```
org.hibernate.AssertionFailure: collection [org.pih.warehouse.core.
LocationType.supportedActivities] was not processed by flush()
        at org.pih.warehouse.inventory.Transaction.getLocalTransfer(Transaction.groovy:122)
        at org.pih.warehouse.requisition.RequisitionService$_rollbackRequisition_closure9.doCall(RequisitionService.groovy:390)
        at org.pih.warehouse.requisition.RequisitionService.rollbackRequisition(RequisitionService.groovy:389)
        at org.pih.warehouse.requisition.RequisitionService$$FastClassByCGLIB$$56b29ff.invoke(<generated>)
        at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:149)
        at org.pih.warehouse.requisition.RequisitionService$$EnhancerByCGLIB$$e2d47ffc.rollbackRequisition(<generated>)
        at org.pih.warehouse.requisition.RequisitionService$rollbackRequisition.call(Unknown Source)
        at org.pih.warehouse.requisition.RequisitionController$_closure31.doCall(RequisitionController.groovy:552)
        at org.pih.warehouse.requisition.RequisitionController$_closure31.doCall(RequisitionController.groovy)
        at grails.plugin.springcache.web.GrailsFragmentCachingFilter.doFilter(GrailsFragmentCachingFilter.groovy:66)
        at net.sf.ehcache.constructs.web.filter.Filter.doFilter(Filter.java:86)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by ewaterman** [comment]
closing this one out as it's many years old and there's a commit that says it fixes the issue
