### ISSUE TITLE
Clicking Batch breadcrumb after clicking Import Product fails

### ISSUE THREAD

**Issue by ghost** [openboxes/openboxes#19]
## Screen Shots:
1. Breadcrumb
   ![screen shot 2013-12-21 at 1 22 24 pm_ob_breadcrumbdefect_1_of_2](https://f.cloud.github.com/assets/6078105/1795720/87fba348-6a32-11e3-8cf3-5974279ae0b7.jpg)
2. Result of Clicking on Batch
   ![screen shot 2013-12-21 at 1 23 53 pm_ob_breadcrumbdefect_2_of_2](https://f.cloud.github.com/assets/6078105/1795722/8c6de24c-6a32-11e3-95a8-cc0558f1efed.jpg)
## OB Version:

© 2013 OpenBoxes    |    Application Version:  0.6.0.5   |    Build Number: v0.5.6-349-g7d67720   |     Environment: development    |    Build Date: 21 Dec 2013 10:17:50 AM  Grails Version:   1.3.7   |    Locale:   English French Spanish    |    Debug Mode: off    |    IP Address:   0:0:0:0:0:0:0:1%0    |    Data load: 0.3s    |    Page load: 0.728s
## StackTrace:

2013-12-21 13:20:00,965 [http-8080-5] INFO  filters.SecurityFilters  - Request duration for (inventory/browse): 248ms/131ms
2013-12-21 13:20:01,055 [http-8080-5] INFO  web.Timer  - Cached request for /openboxes/grails/dashboard/megamenu.dispatch took 0:00:00.002
2013-12-21 13:20:01,750 [http-8080-5] INFO  inventory.InventoryService  - quantity on hand for location Boston Headquarters product 18 Inch Black Screw Driver
2013-12-21 13:20:01,778 [http-8080-5] INFO  inventory.InventoryService  -  \* getQuantityByProductAndInventoryItemMap(): 8 ms
2013-12-21 13:20:01,778 [http-8080-5] INFO  inventory.InventoryService  - getQuantityByProductMap(): 8 ms
2013-12-21 13:20:01,794 [http-8080-5] INFO  filters.SecurityFilters  - Request duration for (json/getQuantityOnHand): 57ms/2ms
2013-12-21 13:20:01,827 [http-8080-1] INFO  filters.SecurityFilters  - Request duration for (json/getQuantityToShip): 53ms/2ms
2013-12-21 13:20:01,838 [http-8080-6] INFO  filters.SecurityFilters  - Request duration for (json/getQuantityToReceive): 71ms/1ms
export products: "ID","SKU","Name","Category","Description","Unit of Measure","Manufacturer","Brand","Manufacturer Code","Manufacturer Name","Vendor","Vendor Code","Vendor Name","Cold Chain","UPC","NDC","Date Created","Date Updated"
"8a80808442e5a19e0142e6e3bd300001","BE75","18 Inch Black Screw Driver","Medical Equipment","Pleasure instrument.","each","ASDS","ASAS","","","","","","false","","","12/Dec/2013 02:59:14","14/Dec/2013 12:32:11"
2013-12-21 13:20:11,114 [http-8080-5] INFO  filters.SecurityFilters  - Request duration for (product/exportAsCsv): 699ms/1ms
2013-12-21 13:20:13,764 [http-8080-5] INFO  batch.BatchController  - ["type":"", "action":"importData", "controller":"batch"]
2013-12-21 13:20:13,764 [http-8080-5] INFO  batch.BatchController  - null
2013-12-21 13:20:14,493 [http-8080-5] INFO  filters.SecurityFilters  - Request duration for (batch/importData): 300ms/728ms
2013-12-21 13:20:14,553 [http-8080-5] INFO  web.Timer  - Cached request for /openboxes/grails/dashboard/megamenu.dispatch took 0:00:00.002
2013-12-21 13:20:15,588 [http-8080-1] INFO  filters.SecurityFilters  - Request duration for (errors/handleNotFound): 343ms/472ms
2013-12-21 13:20:15,595 [http-8080-6] INFO  filters.SecurityFilters  - Request duration for (errors/handleNotFound): 336ms/479ms
2013-12-21 13:20:15,631 [http-8080-5] INFO  filters.SecurityFilters  - Request duration for (errors/handleNotFound): 349ms/516ms
2013-12-21 13:20:15,869 [http-8080-6] INFO  web.Timer  - Cached request for /openboxes/grails/dashboard/megamenu.dispatch took 0:00:00.001
2013-12-21 13:20:15,874 [http-8080-1] INFO  web.Timer  - Cached request for /openboxes/grails/dashboard/megamenu.dispatch took 0:00:00.001
2013-12-21 13:20:16,006 [http-8080-5] INFO  web.Timer  - Cached request for /openboxes/grails/dashboard/megamenu.dispatch took 0:00:00.002
2013-12-21 13:20:51,984 [ContainerBackgroundProcessor[StandardEngine[Tomcat]]] ERROR clickstream.ClickstreamListener  - Cannot get property 'request' on null object
java.lang.NullPointerException: Cannot get property 'request' on null object
    at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:56)
    at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:156)
    at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:44)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:235)
    at grails.plugins.clickstream.logger.ClickStreamLogger.log(ClickStreamLogger.groovy:15)
    at com.opensymphony.clickstream.ClickstreamListener.sessionDestroyed(ClickstreamListener.java:111)
    at org.apache.catalina.session.StandardSession.expire(StandardSession.java:684)
    at org.apache.catalina.session.StandardSession.isValid(StandardSession.java:574)
    at org.apache.catalina.session.ManagerBase.processExpires(ManagerBase.java:680)
    at org.apache.catalina.session.ManagerBase.backgroundProcess(ManagerBase.java:665)
    at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1316)
    at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1601)
    at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1610)
    at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1590)
    at java.lang.Thread.run(Thread.java:680)
2013-12-21 13:23:49,732 [http-8080-5] INFO  filters.SecurityFilters  - Request duration for (batch/index): 11ms/62ms
2013-12-21 13:23:49,778 [http-8080-5] INFO  filters.SecurityFilters  - Request duration for (errors/handleNotFound): 6ms/15ms
2013-12-21 13:23:49,854 [http-8080-5] INFO  web.Timer  - Cached request for /openboxes/grails/dashboard/megamenu.dispatch took 0:00:00.002

**Comment by ewaterman** [comment]
Closing as the newer UI for "import data" does not include this "batch" button.

<img width="933" height="465" alt="Image" src="https://github.com/user-attachments/assets/29d50c11-9714-4f33-87ac-24de0a5446fc" />
