### ISSUE TITLE
SQLException: View's SELECT contains a subquery in the FROM clause

### ISSUE THREAD

**Issue by jmiranda** [openboxes/openboxes#1967]
Upgrading to OpenBoxes 0.8.13 on Debian 9 using MariaDB 10.1.41
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
MariaDB Status
```
root@stockcheck:/opt/tomcat/.grails# service mysql status
● mariadb.service - MariaDB 10.1.41 database server
   Loaded: loaded (/lib/systemd/system/mariadb.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-10-12 15:34:11 UTC; 51min ago
     Docs: man:mysqld(8)
           https://mariadb.com/kb/en/library/systemd/
  Process: 495 ExecStartPost=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
  Process: 493 ExecStartPost=/etc/mysql/debian-start (code=exited, status=0/SUCCESS)
  Process: 329 ExecStartPre=/bin/sh -c [ ! -e /usr/bin/galera_recovery ] && VAR= ||   VAR=`/usr/bin/galera_recovery`; [ $? -eq 0 ]   && systemctl set-environment _WSREP_START_P
  Process: 289 ExecStartPre=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
  Process: 133 ExecStartPre=/usr/bin/install -m 755 -o mysql -g root -d /var/run/mysqld (code=exited, status=0/SUCCESS)
 Main PID: 466 (mysqld)
   Status: "Taking your SQL requests now..."
    Tasks: 41 (limit: 4915)
   CGroup: /system.slice/mariadb.service
           └─466 /usr/sbin/mysqld

Oct 12 15:34:09 stockcheck systemd[1]: mariadb.service: Failed to set invocation ID on control group /system.slice/mariadb.service, ignoring: Operation not permitted
Oct 12 15:34:09 stockcheck systemd[1]: Starting MariaDB 10.1.41 database server...
Oct 12 15:34:10 stockcheck mysqld[466]: 2020-10-12 15:34:10 140095945047424 [Note] /usr/sbin/mysqld (mysqld 10.1.41-MariaDB-0+deb9u1) starting as process 466 ...
Oct 12 15:34:10 stockcheck mysqld[466]: 2020-10-12 15:34:10 140095945047424 [Warning] Could not increase number of max_open_files to more than 4096 (request: 4190)
Oct 12 15:34:11 stockcheck systemd[1]: Started MariaDB 10.1.41 database server.

```
Stacktrace
```
2020-10-12 15:39:42,121 [localhost-startStop-1] INFO  liquibase  - Change set views/changelog.xml::1580848680306-7::jmiranda failed, but failOnError was false
liquibase.exception.JDBCException: Error executing SQL CREATE OR REPLACE VIEW on_order_order_item_summary AS (
SELECT a.product_code, a.name, a.destination_id, sum(a.quantity_ordered) - sum(a.quantity_shipped) as quantity_ordered_not_shipped FROM (
SELECT
        product.product_code,
        product.name,
        order_item.id,
        `order`.destination_id,
        sum(distinct case when `order`.status != 'PENDING' then order_item.quantity else 0 end) as quantity_ordered,
        sum(case when shipment_item.quantity then shipment_item.quantity else 0 end) as quantity_shipped,
        null as quantity_shipped_not_received
    FROM order_item
    JOIN
        product ON order_item.product_id = product.id
    JOIN
        `order` ON order_item.order_id = `order`.id
    LEFT OUTER JOIN
        order_shipment ON order_shipment.order_item_id = order_item.id
    LEFT OUTER JOIN
        shipment_item ON order_shipment.shipment_item_id = shipment_item.id
    LEFT OUTER JOIN
        shipment ON shipment_item.shipment_id = shipment.id
    WHERE `order`.order_type_code = 'PURCHASE_ORDER'
    GROUP BY  product.product_code, order_item.id, product.name, `order`.destination_id ) a
GROUP BY product_code, name, destination_id
)

  at liquibase.database.template.JdbcTemplate.execute(JdbcTemplate.java:55)
  at liquibase.database.template.JdbcTemplate.execute(JdbcTemplate.java:86)
  at liquibase.change.AbstractChange.execute(AbstractChange.java:247)
  at liquibase.change.AbstractChange.executeStatements(AbstractChange.java:93)
  at liquibase.ChangeSet.execute(ChangeSet.java:214)
  at liquibase.parser.visitor.UpdateVisitor.visit(UpdateVisitor.java:26)
  at liquibase.parser.ChangeLogIterator.run(ChangeLogIterator.java:41)
  at liquibase.Liquibase.update(Liquibase.java:112)
  at liquibase.Liquibase$update.call(Unknown Source)
  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:40)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
  at BootStrap$_closure1.doCall(BootStrap.groovy:447)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
  at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1058)
  at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1070)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:886)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:930)
  at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1070)
  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:886)
  at groovy.lang.Closure.call(Closure.java:282)
  at groovy.lang.Closure.call(Closure.java:277)
  at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:251)
  at grails.util.Environment.executeForEnvironment(Environment.java:244)
  at grails.util.Environment.executeForCurrentEnvironment(Environment.java:220)
  at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:59)
  at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:74)
  at org.codehaus.groovy.grails.web.context.GrailsContextLoader.createWebApplicationContext(GrailsContextLoader.java:74)
  at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:197)
  at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47)
  at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5197)
  at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5720)
  at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
  at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1018)
  at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:994)
  at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:662)
  at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1127)
  at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:2020)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: View's SELECT contains a subquery in the FROM clause
  at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
  at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
  at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
  at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491)
  at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2449)
  at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
  at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
  at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
  at liquibase.database.template.JdbcTemplate$1ExecuteStatementCallback.doInStatement(JdbcTemplate.java:78)
  at liquibase.database.template.JdbcTemplate.execute(JdbcTemplate.java:48)
  ... 47 more
```

**Comment by jmiranda** [comment]
We have a bunch of new views that were created in 0.8.13. It seems like MariaDB doesn't like when a view is a SELECT wrapper around another SELECT. See view definition above.

Initial research seems to suggest that we need to create another view for the inner query, 
https://stackoverflow.com/questions/8428641/views-select-contains-a-subquery-in-the-from-clause/42763968

but I'm going to see if I can configure MariaDB to allow the inner SELECT or rework the views to do the query without the inner SELECT.

**Comment by jmiranda** [comment]
This error goes away in MySQL 5.7 / MariaDB 10.2. We don't have official support for MariaDB, but it seems like that version (and subsequent versions) should work.
