### ISSUE TITLE
Cannot save an address due to transient object exception

### ISSUE THREAD

**Issue by berny6969** [openboxes/openboxes#208]
when save address of location get this error

but sometimes save address perfect 👍 

Versión de Grails:   1.3.7    |    Versión de la aplicación:  0.7.20   |    Branch: master   |    Número de compilación: v0.7.18-48-g6266629 

org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: org.pih.warehouse.core.Address

	at org.pih.warehouse.inventory.InventoryService$$EnhancerByCGLIB$$75aed8a8.saveLocation(<generated>)

	at org.pih.warehouse.inventory.InventoryService$saveLocation.call(Unknown Source)

	at org.pih.warehouse.core.LocationController$_closure5.doCall(LocationController.groovy:109)

	at org.pih.warehouse.core.LocationController$_closure5.doCall(LocationController.groovy)

	at grails.plugin.springcache.web.GrailsFragmentCachingFilter.doFilter(GrailsFragmentCachingFilter.groovy:66)

	at net.sf.ehcache.constructs.web.filter.Filter.doFilter(Filter.java:86)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)

	at java.lang.Thread.run(Thread.java:745)

**Comment by jmiranda** [comment]
Thank you for submitting a bug report. I've seen this bug a few times in the past and will try to fix it in the next maintenance release.
