### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by sm2x** [openboxes/openboxes#304]
What is the recommended Development env Ubuntu version, node? npm?, Im using Ubuntu 14.04LTS and $ npm install is keep on failing

**Comment by jmiranda** [comment]
Can you paste the error message you received And include the npm and node versions  you using? 

I had issues with an older version of npm and node. I had to apt-get purge nodejs and installed the latest versions using nvm. 

I’ll add more explicit instructions later this morning.

**Comment by jmiranda** [comment]
Here's what I see when I run test-app with an older version of NodeJS.
```
$ grails test-app :unit
Welcome to Grails 1.3.9 - http://grails.org/
Licensed under Apache Standard License 2.0
Grails home is set to: /home/jmiranda/.sdkman/candidates/grails/current

Base Directory: /home/jmiranda/git/openboxes
Resolving dependencies...
Dependencies resolved in 1356ms.
Running script /home/jmiranda/.sdkman/candidates/grails/current/scripts/TestApp.groovy
Environment set to test
********* loadtest is ignored for environment test.
  [groovyc] Compiling 3 source files to /home/jmiranda/git/openboxes/target/classes
classesDirPath: target/classes
    [mkdir] Created dir: /home/jmiranda/git/openboxes/target/test-reports/html
    [mkdir] Created dir: /home/jmiranda/git/openboxes/target/test-reports/plain

Starting unit test phase ...
Starting React Tests

> openboxes@1.0.0 test /home/jmiranda/git/openboxes
> jest


FAIL src/js/tests/form-elements/SelectField.test.jsx
  ● Test suite failed to run

    /home/jmiranda/git/openboxes/src/js/components/form-elements/SelectField.jsx:44
            return { ...value, value: JSON.stringify(value.value) };
                     ^^^
    SyntaxError: Unexpected token ...

      25 |     const rendered = renderer.create(renderFormField(fieldConfig, 'test-field'));
      26 | 
    > 27 |     expect(rendered.toJSON()).toMatchSnapshot();
      28 |   });
      29 | });
      30 | 
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:316:17)
      at Object.<anonymous> (src/js/tests/form-elements/SelectField.test.jsx:27:20)

FAIL src/js/tests/form-elements/DateField.test.jsx
  ● Test suite failed to run

    /home/jmiranda/git/openboxes/src/js/components/form-elements/BaseReactField.jsx:32
        var attributes = { ...attr, value: input.value, onChange: onChange };
                           ^^^
    SyntaxError: Unexpected token ...

      17 |         <DateTime
      18 |           timeFormat={false}
    > 19 |           closeOnSelect
      20 |           {...attributes}
      21 |           onChange={date => onChange(date)}
      22 |         />
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:316:17)
      at Object.<anonymous> (src/js/components/form-elements/DateField.jsx:19:23)
      at Object.<anonymous> (src/js/tests/form-elements/DateField.test.jsx:27:18)

PASS src/js/tests/api-client/apiClient.test.js
  apiClient
    ✓ returns 200 (21ms)
    ✓ returns 400 (8ms)
    ✓ returns 401 (5ms)
    ✓ returns 403 (5ms)
    ✓ returns 404 (3ms)
    ✓ returns 500 (4ms)

FAIL src/js/tests/form-elements/ArrayField.test.jsx
  ● Test suite failed to run

    /home/jmiranda/git/openboxes/src/js/components/form-elements/FieldArrayComponent.jsx:116
                            ...properties,
                            ^^^
    SyntaxError: Unexpected token ...

      15 |       fieldsConfig={fieldConfig}
      16 |       properties={otherProps}
    > 17 |     />
      18 |   );
      19 | };
      20 | 
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:316:17)
      at Object.<anonymous> (src/js/components/form-elements/ArrayField.jsx:17:28)
      at Object.<anonymous> (src/js/tests/form-elements/ArrayField.test.jsx:35:19)

FAIL src/js/tests/form-elements/ButtonField.test.jsx
  ● Test suite failed to run

    /home/jmiranda/git/openboxes/src/js/components/form-elements/ButtonField.jsx:28
      var attr = { ...attributes, ...dynamicAttr };
                   ^^^
    SyntaxError: Unexpected token ...

      25 |   });
      26 | 
    > 27 |   it('component label', () => {
      28 |     const fieldConfig = {
      29 |       type: ButtonField,
      30 |       buttonLabel: () => <span>test label</span>,
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:316:17)
      at Object.<anonymous> (src/js/tests/form-elements/ButtonField.test.jsx:27:20)

FAIL src/js/tests/form-elements/TextField.test.jsx
  ● Test suite failed to run

    /home/jmiranda/git/openboxes/src/js/components/form-elements/BaseHtmlField.jsx:35
        var attributes = { ...attr, value: input.value, onChange: onChange };
                           ^^^
    SyntaxError: Unexpected token ...

      11 |     />
      12 |   );
    > 13 | 
      14 |   return (
      15 |     <BaseHtmlField
      16 |       {...props}
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:316:17)
      at Object.<anonymous> (src/js/components/form-elements/TextField.jsx:13:22)
      at Object.<anonymous> (src/js/tests/form-elements/TextField.test.jsx:27:18)

FAIL src/js/tests/form-elements/CheckboxField.test.jsx
  ● Test suite failed to run

    /home/jmiranda/git/openboxes/src/js/components/form-elements/CheckboxField.jsx:31
        var attributes = { ...input, ...attr, onChange: onChange };
                           ^^^
    SyntaxError: Unexpected token ...

      25 |   });
      26 | });
    > 27 | 
      28 | 
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:316:17)
      at Object.<anonymous> (src/js/tests/form-elements/CheckboxField.test.jsx:27:22)

FAIL src/js/tests/form-elements/BaseField.test.jsx
  ● Test suite failed to run

    /home/jmiranda/git/openboxes/src/js/components/form-elements/BaseField.jsx:87
              ...attributes,
              ^^^
    SyntaxError: Unexpected token ...

      25 | 
      26 |     expect(rendered.toJSON()).toMatchSnapshot();
    > 27 |   });
      28 | 
      29 |   it('component label', () => {
      30 |     const props = {
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:316:17)
      at Object.<anonymous> (src/js/tests/form-elements/BaseField.test.jsx:27:18)

PASS src/js/tests/form-elements/WizardSteps.test.jsx
  ✓ WizardSteps renders correctly (14ms)

Test Suites: 7 failed, 2 passed, 9 total
Tests:       7 passed, 7 total
Snapshots:   1 passed, 1 total
Time:        1.644s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openboxes@1.0.0 test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openboxes@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jmiranda/.npm/_logs/2018-06-18T16_19_25_435Z-debug.log

Tests FAILED
```

**Comment by jmiranda** [comment]
So I installed nvm (https://github.com/creationix/nvm/blob/master/README.md) and installed node from there.
```
$ node -v
v6.6.0
$ which node
/home/jmiranda/.nvm/versions/node/v6.6.0/bin/node
$ nvm install node
v10.4.1 is already installed.
Now using node v10.4.1 (npm v6.1.0)
```
This installs the latest version of node, but does not set this as the default going forward. Therefore it'll work in the current bash session but not if you open a new terminal window.

Here's what I see if I open a new terminal window.
```
$ nvm list node
         v4.5.0  
->       v6.6.0  
        v10.4.0  
        v10.4.1  
```
Therefore you either need to use `nvm use` to set the correct version every time you open a new terminal window.
```
$ nvm use node v10.4.1
Now using node v10.4.1 (npm v6.1.0)
```
Let me know if you figure out a way to set the default version.

**Comment by sm2x** [comment]
ok, i will try this and will let you know, thanks a lot

**Comment by jmiranda** [comment]
You can also set the default node version https://eric.blog/2016/08/23/set-default-node-version-with-nvm/
