### ISSUE TITLE
NullPointerException: Cannot get property 'inventoryItem' on null object

### ISSUE THREAD

**Issue by jmiranda** [openboxes/openboxes#39]
Email from Kelsey 

> I have been trying to run a consumption report in the Malawi instance of open boxes, but every time I try I get an error. The error reads as follows:
> 
> ```
> java.lang.NullPointerException: Cannot get property 'inventoryItem' on null object
>         at org.pih.warehouse.reporting.ConsumptionController$_closure1_closure5_closure10.doCall(ConsumptionController.groovy:116)
>         at org.pih.warehouse.reporting.ConsumptionController$_closure1_closure5.doCall(ConsumptionController.groovy:115)
>         at org.pih.warehouse.reporting.ConsumptionController$_closure1.doCall(ConsumptionController.groovy:104)
>         at org.pih.warehouse.reporting.ConsumptionController$_closure1.call(ConsumptionController.groovy)
>         at grails.plugin.springcache.web.GrailsFragmentCachingFilter.doFilter(GrailsFragmentCachingFilter.groovy:66)
>         at net.sf.ehcache.constructs.web.filter.Filter.doFilter(Filter.java:86)
>         at java.lang.Thread.run(Thread.java:662)
> ```

**Comment by jmiranda** [comment]
Fixed
