### ISSUE TITLE
Boxes (sub-containers) cannot be deleted once created 

### ISSUE THREAD

**Issue by jmiranda** [openboxes/openboxes#40]
Stacktrace:
```
Exception occured invoking flow action: deleted object would be re-saved by cascade (remove deleted object from associations): [org.pih.warehouse.shipping.Container#c87937524c4a6871014c4c4c315d000d]; nested exception is org.hibernate.ObjectDeletedException: deleted object would be re-saved by cascade (remove deleted object from associations): [org.pih.warehouse.shipping.Container#c87937524c4a6871014c4c4c315d000d]
org.springframework.dao.InvalidDataAccessApiUsageException: deleted object would be re-saved by cascade (remove deleted object from associations): [org.pih.warehouse.shipping.Container#c87937524c4a6871014c4c4c315d000d]; nested exception is org.hibernate.ObjectDeletedException: deleted object would be re-saved by cascade (remove deleted object from associations): [org.pih.warehouse.shipping.Container#c87937524c4a6871014c4c4c315d000d]
        at org.pih.warehouse.shipping.ShipmentService$$EnhancerByCGLIB$$5fd78b1a.deleteContainer(<generated>)
        at org.pih.warehouse.shipping.ShipmentService$deleteContainer.call(Unknown Source)
        at org.pih.warehouse.shipping.CreateShipmentWorkflowController$_closure2_closure11_closure41.doCall(CreateShipmentWorkflowController.groovy:224)
        at grails.plugin.springcache.web.GrailsFragmentCachingFilter.doFilter(GrailsFragmentCachingFilter.groovy:66)
        at net.sf.ehcache.constructs.web.filter.Filter.doFilter(Filter.java:86)
        at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
        at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291)
        at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:776)
        at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:705)
        at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:898)
        at java.lang.Thread.run(Thread.java:662)
Caused by: org.hibernate.ObjectDeletedException: deleted object would be re-saved by cascade (remove deleted object from associations): [org.pih.warehouse.shipping.Container#c87937524c4a6871014c4c4c315d000d]
        ... 11 more
```

Clickstream: 
```
Clickstream for 209.156.249.193

Initial Referrer: http://staging.pih-emr.org/openboxes/js/jquery.ui/css/smoothness/jquery-ui.css
Hostname: 209.156.249.193
Session ID: CE74D829AC80012D63DB3177D7B1A82E
Bot: No
Stream Start: 24/Mar/2015 04:42:08 PM UTC
Last Request: 24/Mar/2015 04:48:11 PM UTC
Session Length: 6 minutes 3 seconds
# of Requests: 34
Click stream:

staging.pih-emr.org/openboxes/js/jquery.ui/css/smoothness/images/ui-icons_454545_256x240.png
staging.pih-emr.org/openboxes/createShipmentWorkflow/createShipment?containerToEditId=c87937524c4a6871014c4c4c315d000d&execution=e1s29&_eventId=editContainer
staging.pih-emr.org/openboxes/auth/login
staging.pih-emr.org/openboxes/plugins/yui-2.8.2.1/js/yui/reset-fonts-grids/reset-fonts-grids.css
staging.pih-emr.org/openboxes/plugins/jquery-ui-1.8.7/jquery-ui/themes/ui-lightness/jquery-ui-1.8.7.custom.css
staging.pih-emr.org/openboxes/plugins/jquery-validation-ui-1.4.7/js/qTip/jquery.qtip.pack.js
staging.pih-emr.org/openboxes/plugins/jquery-validation-ui-1.4.7/js/jquery-validation-ui/grails-validation-methods.js
staging.pih-emr.org/openboxes/plugins/jquery-ui-1.8.7/jquery-ui/js/jquery-ui-1.8.7.custom.min.js
staging.pih-emr.org/openboxes/plugins/jquery-validation-ui-1.4.7/css/qTip/jquery.qtip.css
staging.pih-emr.org/openboxes/plugins/jquery-validation-1.9/js/jquery-validation/jquery.validate.min.js
staging.pih-emr.org/openboxes/plugins/jquery-1.7.2/js/jquery/jquery-1.7.2.min.js
staging.pih-emr.org/openboxes/auth/handleLogin
staging.pih-emr.org/openboxes/dashboard/index
staging.pih-emr.org/openboxes/dashboard/chooseLocation
staging.pih-emr.org/openboxes/dashboard/chooseLocation/3
staging.pih-emr.org/openboxes/createShipmentWorkflow/createShipment?containerToEditId=c87937524c4a6871014c4c4c315d000d&execution=e1s29&_eventId=editContainer
staging.pih-emr.org/openboxes/createShipmentWorkflow/createShipment?containerToEditId=c87937524c4a6871014c4c4c315d000d&_eventId=editContainer
staging.pih-emr.org/openboxes/createShipmentWorkflow/createShipment?execution=e1s1&containerToEditId=c87937524c4a6871014c4c4c315d000d
staging.pih-emr.org/openboxes/shipment/list?type=incoming&execution=e1s1
staging.pih-emr.org/openboxes/shipment/list?type=incoming&status=PENDING&execution=e1s1
staging.pih-emr.org/openboxes/images/icons/shipmentType/ShipmentTypeLand.png
staging.pih-emr.org/openboxes/images/icons/shipmentType/ShipmentTypeAir.png
staging.pih-emr.org/openboxes/shipment/showDetails/c87937524c4a6871014c4c4a50590001
staging.pih-emr.org/openboxes/images/icons/silk/page.png
staging.pih-emr.org/openboxes/images/icons/silk/date.png
staging.pih-emr.org/openboxes/doc4j/downloadPackingList/c87937524c4a6871014c4c4a50590001
staging.pih-emr.org/openboxes/createShipmentWorkflow/createShipment/c87937524c4a6871014c4c4a50590001
staging.pih-emr.org/openboxes/createShipmentWorkflow/createShipment/c87937524c4a6871014c4c4a50590001?execution=e2s1
staging.pih-emr.org/openboxes/createShipmentWorkflow/createShipment?execution=e2s1&_eventId=enterContainerDetails
staging.pih-emr.org/openboxes/createShipmentWorkflow/createShipment?execution=e2s2
staging.pih-emr.org/openboxes/createShipmentWorkflow/createShipment?container.id=c87937524c4a6871014c4c4c315d000d&execution=e2s2&_eventId=deleteContainer
staging.pih-emr.org/openboxes/createShipmentWorkflow/createShipment?execution=e2s2
staging.pih-emr.org/openboxes/createShipmentWorkflow/createShipment?container.id=c87937524c4a6871014c4c4c315d000d&execution=e2s2&_eventId=deleteContainer
staging.pih-emr.org/openboxes/createShipmentWorkflow/createShipment?execution=e2s2
```

**Comment by jmiranda** [comment]
Another similar issue occurred when Kelsey tried to delete a box from within a pallet
> Tried to delete an empty box from a pallet and received this error message

Stacktrace:
```
org.codehaus.groovy.grails.web.errors.GrailsWrappedRuntimeException: deleted object would be re-saved by cascade (remove deleted object from associations): [org.pih.warehouse.shipping.Container#c879370c4be8a6b1014beaa167fe031b]
	at org.codehaus.groovy.grails.web.errors.GrailsExceptionResolver.resolveException(GrailsExceptionResolver.java:79)
	at org.springframework.web.servlet.DispatcherServlet.processHandlerException(DispatcherServlet.java:987)
	at org.codehaus.groovy.grails.web.servlet.GrailsDispatcherServlet.doDispatch(GrailsDispatcherServlet.java:319)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:549)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:70)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:70)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at javax.servlet.FilterChain$doFilter.call(Unknown Source)
	at grails.plugin.springcache.web.GrailsFragmentCachingFilter.doFilter(GrailsFragmentCachingFilter.groovy:66)
	at net.sf.ehcache.constructs.web.filter.Filter.doFilter(Filter.java:86)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:70)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:646)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:436)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:374)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:302)
	at org.codehaus.groovy.grails.web.util.WebUtils.forwardRequestForUrlMappingInfo(WebUtils.java:298)
	at org.codehaus.groovy.grails.web.util.WebUtils.forwardRequestForUrlMappingInfo(WebUtils.java:264)
	at org.codehaus.groovy.grails.web.util.WebUtils.forwardRequestForUrlMappingInfo(WebUtils.java:255)
	at org.codehaus.groovy.grails.web.mapping.filter.UrlMappingsFilter.doFilterInternal(UrlMappingsFilter.java:183)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter.obtainContent(GrailsPageFilter.java:245)
	at org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter.doFilter(GrailsPageFilter.java:134)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.codehaus.groovy.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:69)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.codehaus.groovy.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:69)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.opensymphony.clickstream.ClickstreamFilter.doFilter(ClickstreamFilter.java:56)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
	at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291)
	at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:776)
	at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:705)
	at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:898)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.springframework.webflow.execution.ActionExecutionException: Exception thrown executing org.codehaus.groovy.grails.webflow.engine.builder.ClosureInvokingAction@10e9cc2 in state 'enterContainerDetails' of flow 'createShipmentWorkflow/createShipment' -- action execution attributes were 'map[[empty]]'
	at grails.plugin.springcache.web.GrailsFragmentCachingFilter.doFilter(GrailsFragmentCachingFilter.groovy:66)
	at net.sf.ehcache.constructs.web.filter.Filter.doFilter(Filter.java:86)
	at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
	at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291)
	at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:776)
	at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:705)
	at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:898)
	... 1 more
Caused by: org.springframework.dao.InvalidDataAccessApiUsageException: deleted object would be re-saved by cascade (remove deleted object from associations): [org.pih.warehouse.shipping.Container#c879370c4be8a6b1014beaa167fe031b]; nested exception is org.hibernate.ObjectDeletedException: deleted object would be re-saved by cascade (remove deleted object from associations): [org.pih.warehouse.shipping.Container#c879370c4be8a6b1014beaa167fe031b]
	at org.pih.warehouse.shipping.ShipmentService$$EnhancerByCGLIB$$a46b9840.deleteContainer()
	at org.pih.warehouse.shipping.ShipmentService$deleteContainer.call(Unknown Source)
	at org.pih.warehouse.shipping.CreateShipmentWorkflowController$_closure2_closure11_closure41.doCall(CreateShipmentWorkflowController.groovy:224)
	... 8 more
Caused by: org.hibernate.ObjectDeletedException: deleted object would be re-saved by cascade (remove deleted object from associations): [org.pih.warehouse.shipping.Container#c879370c4be8a6b1014beaa167fe031b]
	... 11 more
```
