### ISSUE TITLE
Automate dbdocs action to convert generated SQL to DBML

### ISSUE THREAD

**Issue by jmiranda** [openboxes/openboxes#4049]
After talking to the dbdocs team about the service I realized we're not automatically updating openboxes.dbml in the source code. In fact, we're not even periodically updating it manually. It would be great to use Hibernate export-schema or Liquibase to export SQL that can be converted to DBML and used to publish the documentation. 

We might need to manually update the openboxes.dbml file in order to add grouping, descriptions, etc. 

We might also want to restrict updates to PRs merged to develop rather than ALL commits/PRs.

**Comment by jmiranda** [comment]
Thinking this might be low-hanging fruit, I took a crack at this tonight.
https://community.dbdiagram.io/t/anyone-have-success-setting-up-a-continuous-integration-using-github-actions/1465

Checkout code 
```
git checkout feature/upgrade-to-grails-3.3.10
git checkout -b 4094-automate-dbdocs
```
Install / configure dependencies
```
npm install dbdocs
sdk use grails 3.3.18
sdk use java 8.0.302-open
```
Export schema 
```
grails schema-export
```
Error
```
Caused by: org.gradle.execution.TaskSelectionException: Task 'schemaExport' not found in root project 'openboxes'.
	at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:116)
	at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:81)
	at org.gradle.execution.commandline.CommandLineTaskParser.parseTasks(CommandLineTaskParser.java:42)
	at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:44)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
	at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:44)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
	at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:47)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.select(DefaultBuildConfigurationActionExecuter.java:36)
	at org.gradle.initialization.DefaultGradleLauncher$CalculateTaskGraph.run(DefaultGradleLauncher.java:305)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.initialization.DefaultGradleLauncher.constructTaskGraph(DefaultGradleLauncher.java:190)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:145)
	... 67 more
```
Needed to add Hibernate5 plugin to classpath 
```
dependencies {
        classpath "com.bertramlabs.plugins:asset-pipeline-gradle:${assetPipelineVersion}"
        classpath "org.grails:grails-gradle-plugin:${grailsVersion}"
        classpath "org.grails.plugins:database-migration:${databaseMigrationVersion}"
        classpath "org.grails.plugins:views-gradle:${grailsViewsVersion}"
        classpath "org.owasp:dependency-check-gradle:${owaspVersion}"
        classpath "org.grails.plugins:hibernate5:${gormVersion - '.RELEASE'}"

    }
```
Trying again
```
grails schema-export
```
Success
```
024-04-26 21:14:29,659  INFO [main      ] grails.boot.GrailsApp                   : Application starting in environment: development
Generating script to ./build/ddl.sql in environment 'development' for the default DataSource
2024-04-26 21:14:29,977  INFO [main      ] org.hibernate.tool.hbm2ddl.SchemaExport : HHH000227: Running hbm2ddl schema export
2024-04-26 21:14:30,029  INFO [main      ] o.h.t.schema.internal.SchemaCreatorImpl : HHH000476: Executing import script 'org.hibernate.tool.schema.internal.exec.ScriptSourceInputNonExistentImpl@5d73530f'
2024-04-26 21:14:30,032  INFO [Thread-12 ] g.u.s.DevelopmentWebApplicationContext  : Closing grails.ui.support.DevelopmentWebApplicationContext@7a3e5cd3: startup date [Fri Apr 26 21:13:40 CDT 2024]; root of context hierarchy
```

**Comment by jmiranda** [comment]
Ok, now we have a generated file here and we just need to pass this to dbdocs. 
```
./build/ddl.sql
```
But first, we install dbdocs
```
npm install -g dbdocs
```
Success
```
pm WARN deprecated @oclif/screen@3.0.8: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
/home/jmiranda/.nvm/versions/node/v14.19.0/bin/dbdocs -> /home/jmiranda/.nvm/versions/node/v14.19.0/lib/node_modules/dbdocs/bin/run
npm WARN notsup Unsupported engine for antlr4@4.13.1: wanted: {"node":">=16"} (current: {"node":"14.19.0","npm":"6.14.16"})
npm WARN notsup Not compatible with your version of node/npm: antlr4@4.13.1

+ dbdocs@0.9.2
added 245 packages from 157 contributors in 13.369s
```
and the dbml CLI tool
```
npm install -g @dbml/cli
/home/jmiranda/.nvm/versions/node/v14.19.0/bin/dbml2sql -> /home/jmiranda/.nvm/versions/node/v14.19.0/lib/node_modules/@dbml/cli/bin/dbml2sql.js
/home/jmiranda/.nvm/versions/node/v14.19.0/bin/sql2dbml -> /home/jmiranda/.nvm/versions/node/v14.19.0/lib/node_modules/@dbml/cli/bin/sql2dbml.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/@dbml/cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for antlr4@4.13.1: wanted: {"node":">=16"} (current: {"node":"14.19.0","npm":"6.14.16"})
npm WARN notsup Not compatible with your version of node/npm: antlr4@4.13.1
npm WARN @babel/cli@7.24.1 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.

+ @dbml/cli@3.4.3
added 86 packages from 56 contributors in 6.923s
```
Convert the SQL DDL file to DBML
```
sql2dbml ./build/ddl.sql --mysql -o schema.dbml
```
Huzzah 
```
  ✔ Generated DBML file from SQL file (MySQL): schema.dbml
```
And now we build the dbdocs ...
```
dbdocs build schema.dbml
✖ Failed: Something wrong :( Please try again.
```
Doh.

**Comment by jmiranda** [comment]
Oops forgot to login 
```
$ dbdocs login
? Choose a login method: GitHub/Google
? Please input your authentication token:  <token>
✔ Validate token
✔ Save credential
```
Let's try it again.
```
$ dbdocs build schema.dbml
✖ Failed: Something wrong :( Please try again.
```

**Comment by jmiranda** [comment]
I got to the place where we convert SQL to DBML and it fails.
```
$ sql2dbml ./build/ddl.sql --mysql -o openboxes.dbml
/home/jmiranda/n/lib/node_modules/@dbml/cli/node_modules/@so-ric/colorspace/dist/index.cjs.js:1976
		(limiters[m] ||= [])[channel] = modifier;
		             ^^^

SyntaxError: Unexpected token '||='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/jmiranda/n/lib/node_modules/@dbml/cli/node_modules/@dabh/diagnostics/modifiers/namespace-ansi.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```
I upgraded to node 20.19.5
```
$ n 20
  installing : node-v20.19.5
       mkdir : /home/jmiranda/n/n/versions/node/20.19.5
       fetch : https://nodejs.org/dist/v20.19.5/node-v20.19.5-linux-x64.tar.xz
     copying : node/20.19.5
   installed : v20.19.5 (with npm 10.8.2)
```
and the conversion worked
```
$ sql2dbml ./build/ddl.sql --mysql -o openboxes.dbml
  ✔ Generated DBML file from SQL file (MySQL): openboxes.dbml
```
logged into dbdocs using a token 
```
$ dbdocs login
✔ Choose a login method: GitHub/Google
✔ Please input your authentication token:  <redacted>
✔ Validate token
✔ Save credential
```
and then i ran a build 
```
$ dbdocs build openboxes.dbml 
✔ Parsing file content
✔ Username: (jmiranda) 
✔ Project name:  openboxes
⚠ Project 'openboxes' is public, consider setting password or restricting access to it
✔ Done. Visit: https://dbdocs.io/jmiranda/OpenBoxes
```
and the project has been updated https://dbdocs.io/jmiranda/openboxes

**Comment by jmiranda** [comment]
Here's the github action log showing the potential problem from the automated build. 

https://productionresultssa3.blob.core.windows.net/actions-results/b041fd3e-b49e-4eff-acbb-094c2f54c78a/workflow-job-run-172bc47c-6d4e-5b9a-a3e4-47640f502a35/logs/job/job-logs.txt?rsct=text%2Fplain&se=2025-10-15T18%3A39%3A35Z&sig=tKY5PXXnag2nxZTtRxSQvvuBf7Y7Thb03%2BoQyXHegFQ%3D&ske=2025-10-16T02%3A39%3A25Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-10-15T14%3A39%3A25Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-11-05&sp=r&spr=https&sr=b&st=2025-10-15T18%3A29%3A30Z&sv=2025-11-05

There are two issues that might be contributing 

1. The schema export is trying to start up a full instance of openboxes including the database. However, we haven't configured a database so the connection pool creation is failing. 
```
2025-10-02T18:45:43.6940932Z <============-> 93% EXECUTING [5m 47s]> IDLE> :schemaExport> IDLE> IDLE<============-> 93% EXECUTING [5m 47s]> :schemaExport<============-> 93% EXECUTING [5m 48s]> :schemaExport<============-> 93% EXECUTING [5m 48s]> :schemaExport<============-> 93% EXECUTING [5m 48s]> :schemaExport2025-10-02 18:45:43,620 ERROR [main] o.apache.tomcat.jdbc.pool.ConnectionPool: Unable to create initial connections of pool.
2025-10-02T18:45:43.6945922Z com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
2025-10-02T18:45:43.6946501Z 
2025-10-02T18:45:43.6947120Z The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
```

This might not cause an issue if the schema export does not rely on the database, but that's probably unlikely ... so we'll need to at least configure this to use a testcontainer. 

2. The second issue is that when we run the dbdocs build, we're prompted for a project name. It's very possible that the prompt is causing the dbdocs build to timeout and fail. Therefore, adding the project as a command-line argument would avoid the prompt. 

```
$ dbdocs build openboxes.dbml --project=openboxes
✔ Parsing file content
⚠ Project 'openboxes' is public, consider setting password or restricting access to it
✔ Done. Visit: https://dbdocs.io/jmiranda/openboxes
```

**Comment by jmiranda** [comment]
Build 5890 was executed manually from the command line.

Build 5892 was executed via Github Actions 
https://github.com/openboxes/openboxes/actions/runs/18541284545/job/52849175995

<img width="3837" height="1925" alt="Image" src="https://github.com/user-attachments/assets/f28fda51-0297-49bd-a826-67dc67f1711b" />
