### ISSUE TITLE
error while running openboxes using docker 

### ISSUE THREAD

**Issue by nivl98** [openboxes/openboxes#4696]
step by step: 

git clone git@github.com:openboxes/openboxes.git
git clone git@github.com:openboxes/openboxes-docker.git
cd openboxes-docker
docker-compose up --build

error thrown: 

openboxes-docker-grails-1  | added 1446 packages from 972 contributors and audited 1448 packages in 352.358s
openboxes-docker-grails-1  | found 6 vulnerabilities (1 low, 3 moderate, 1 high, 1 critical)
openboxes-docker-grails-1  |   run `npm audit fix` to fix them, or `npm audit` for details
openboxes-docker-grails-1  | npm verb exit [ 0, true ]
openboxes-docker-grails-1  | npm timing npm Completed in 353301ms
openboxes-docker-grails-1  | npm info ok 
openboxes-docker-grails-1  | Welcome to Grails 1.3.9 - http://grails.org/
openboxes-docker-grails-1  | Licensed under Apache Standard License 2.0
openboxes-docker-grails-1  | Grails home is set to: /root/.sdkman/candidates/grails/current
openboxes-docker-grails-1  | 
openboxes-docker-grails-1  | Base Directory: /app
openboxes-docker-grails-1  | Resolving dependencies...
openboxes-docker-grails-1  | Dependencies resolved in 1836ms.
openboxes-docker-grails-1  | Running script /root/.sdkman/candidates/grails/current/scripts/RunApp.groovy
openboxes-docker-grails-1  | Environment set to development
openboxes-docker-grails-1  |      [copy] Copied 3 empty directories to 2 empty directories under /root/.grails/1.3.9/projects/app/resources
openboxes-docker-grails-1  |     [mkdir] Created dir: /root/.grails/1.3.9/projects/app/plugin-classes
openboxes-docker-grails-1  |   [groovyc] Compiling 4 source files to /root/.grails/1.3.9/projects/app/plugin-classes
openboxes-docker-grails-1  |     [mkdir] Created dir: /root/.grails/1.3.9/projects/app/classes
openboxes-docker-grails-1  |   [groovyc] Compiling 428 source files to /root/.grails/1.3.9/projects/app/classes
openboxes-docker-grails-1  |   [groovyc] org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
openboxes-docker-grails-1  |   [groovyc] /app/grails-app/controllers/org/pih/warehouse/api/CombinedShipmentItemApiController.groovy: 76: unexpected token: ? @ line 76, column 21.
openboxes-docker-grails-1  |   [groovyc]                        ? OrderItem.findAllByOrderInListAndProduct(orders, product)
openboxes-docker-grails-1  |   [groovyc]                        ^
openboxes-docker-grails-1  |   [groovyc] 
openboxes-docker-grails-1  |   [groovyc] 1 error
openboxes-docker-grails-1  | Compilation error: Compilation Failed
openboxes-docker-grails-1 exited with code 1

any suggestions?

**Comment by EWaterman** [comment]
Which branch of openboxes are you on? You may need to modify the grails and node versions in your Dockerfile to match the versions there. For example, the  `develop` branch has been upgraded to Grails 3, so you'd want something like:
```
ENV GRAILS_VERSION=3.3.10
```

That said, it's also very possible that our Docker scripts have fallen somewhat out of date. I'd love for someone to take a shot at bringing them more up to date with the current state of the application, especially since we're looking to support Docker more as a part of CI flows.

**Comment by nivl98** [comment]
I couldn't solve it. Yes, probably should be updated. Thanks.

**Comment by jmiranda** [comment]
It's definitely an issue with docker resources not being upgraded along with the Grails 3 migration. I'm going to reopen this ticket so we can look into it when we have a minute.

**Comment by Sampppp** [comment]
I go the exact same error and I also tried changing `ENV GRAILS_VERSION=3.3.17` in `./openboxes-docker/grails-java7/Dockerfile`

Then in the same file, I tried changing `FROM azul/zulu-openjdk:8u392-8.74.0.17` and `ENV JAVA_HOME /usr/lib/jvm/zulu8`

but then that resulted in the error:
```shell
Unzipping /root/.gradle/wrapper/dists/gradle-4.10.3-bin/31t79e2qsceia4mkbojplrgx/gradle-4.10.3-bin.zip to /root/.gradle/wrapper/dists/gradle-4.10.3-bin/31t79e2qsceia4mkbojplrgx
grails_1  | Set executable permissions for: /root/.gradle/wrapper/dists/gradle-4.10.3-bin/31t79e2qsceia4mkbojplrgx/gradle-4.10.3/bin/gradle
grails_1  | 
grails_1  | > Configure project :
grails_1  | configuring for a standalone environment...
grails_1  | 
grails_1  | CONFIGURE SUCCESSFUL in 27s
grails_1  | | Error Command [run-app] error: could not determine a constructor for the tag tag:yaml.org,2002:java.util.Map
grails_1  |  in 'reader', line 1, column 1:
grails_1  |     description:
grails_1  |     ^
grails_1  |  (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
grails_1  | could not determine a constructor for the tag tag:yaml.org,2002:java.util.Map
grails_1  |  in 'reader', line 1, column 1:
grails_1  |     description:
grails_1  |     ^
grails_1  | 
grails_1  |     at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructUndefined.construct(SafeConstructor.java:617)
grails_1  |     at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264)
grails_1  |     at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247)
grails_1  |     at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:201)
grails_1  |     at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:185)
grails_1  |     at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:493)
grails_1  |     at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:486)
grails_1  |     at org.grails.cli.profile.commands.factory.YamlCommandFactory.readCommandFile(YamlCommandFactory.groovy:57)
grails_1  |     at org.grails.cli.profile.commands.factory.YamlCommandFactory.readCommandFile(YamlCommandFactory.groovy)
grails_1  |     at org.grails.cli.profile.commands.factory.ResourceResolvingCommandFactory.findCommands(ResourceResolvingCommandFactory.groovy:44)
grails_1  |     at org.grails.cli.profile.commands.CommandRegistry.findCommands(CommandRegistry.groovy:86)
grails_1  |     at org.grails.cli.profile.commands.CommandRegistry.findCommands(CommandRegistry.groovy)
grails_1  |     at org.grails.cli.profile.AbstractProfile.getCommands(AbstractProfile.groovy:440)
grails_1  |     at org.grails.cli.profile.repository.AbstractJarProfileRepository$JarProfile.getCommands(AbstractJarProfileRepository.groovy:130)
grails_1  |     at org.grails.cli.profile.AbstractProfile.registerParentCommands(AbstractProfile.groovy:453)
grails_1  |     at org.grails.cli.profile.AbstractProfile.getCommands(AbstractProfile.groovy:445)
grails_1  |     at org.grails.cli.profile.repository.AbstractJarProfileRepository$JarProfile.getCommands(AbstractJarProfileRepository.groovy:130)
grails_1  |     at org.grails.cli.profile.AbstractProfile.registerParentCommands(AbstractProfile.groovy:453)
grails_1  |     at org.grails.cli.profile.AbstractProfile.getCommands(AbstractProfile.groovy:445)
grails_1  |     at org.grails.cli.profile.repository.AbstractJarProfileRepository$JarProfile.getCommands(AbstractJarProfileRepository.groovy:130)
grails_1  |     at org.grails.cli.profile.AbstractProfile.handleCommand(AbstractProfile.groovy:470)
grails_1  |     at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:377)
grails_1  |     at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:350)
grails_1  |     at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:271)
grails_1  |     at org.grails.cli.GrailsCli.main(GrailsCli.groovy:159)
grails_1  | | Error Command [run-app] error: could not determine a constructor for the tag tag:yaml.org,2002:java.util.Map
grails_1  |  in 'reader', line 1, column 1:
grails_1  |     description:
grails_1  |     ^
```

**Comment by Sampppp** [comment]
I got the exact same error and I also tried changing `ENV GRAILS_VERSION=3.3.170` in `./openboxes-docker/grails-java7/Dockerfile`

Then in the same file, I tried changing `FROM azul/zulu-openjdk:8u392-8.74.0.17` and `ENV JAVA_HOME /usr/lib/jvm/zulu8`

Then after some kind of react dependency error I deleted `./build/.dependencies`

Things took a bit to compile, but then it lead to this error

```shell
grails_1  | BUILD FAILED in 6m 53s
grails_1  | 6 actionable tasks: 6 executed
grails_1  | 
grails_1  | 
grails_1  | 
grails_1  | 
grails_1  | 
grails_1  | <-------------> 0% WAITING> IDLE> IDLE> IDLE> IDLE<-------------> 0% WAITING| Error Failed to start server
grails_1  | java.util.concurrent.ExecutionException: org.gradle.tooling.BuildException: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-4.10.3-bin.zip'.
grails_1  |     at java.util.concurrent.FutureTask.report(FutureTask.java:122)
grails_1  |     at java.util.concurrent.FutureTask.get(FutureTask.java:192)
grails_1  |     at java_util_concurrent_Future$get.call(Unknown Source)
grails_1  |     at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
grails_1  |     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
grails_1  |     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
grails_1  |     at run-app.run(run-app.groovy:89)
grails_1  |     at org.grails.cli.profile.commands.script.GroovyScriptCommand.handle(GroovyScriptCommand.groovy:152)
grails_1  |     at org.grails.cli.profile.AbstractProfile.handleCommand(AbstractProfile.groovy:481)
grails_1  |     at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:377)
grails_1  |     at org.grails.cli.GrailsCli.handleCommand(GrailsCli.groovy:350)
grails_1  |     at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:271)
grails_1  |     at org.grails.cli.GrailsCli.main(GrailsCli.groovy:159)
grails_1  | Caused by: org.gradle.tooling.BuildException: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-4.10.3-bin.zip'.
grails_1  |     at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:51)
grails_1  |     at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29)
grails_1  |     at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:41)
grails_1  |     at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57)
grails_1  |     at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
grails_1  |     at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
grails_1  |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
grails_1  |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
grails_1  |     at java.lang.Thread.run(Thread.java:750)
grails_1  |     at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
grails_1  |     at org.gradle.tooling.internal.consumer.DefaultBuildLauncher.run(DefaultBuildLauncher.java:77)
grails_1  |     at org.grails.cli.gradle.GradleUtil$_runBuildWithConsoleOutput_closure3.doCall(GradleUtil.groovy:97)
grails_1  |     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
grails_1  |     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
grails_1  |     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
grails_1  |     at java.lang.reflect.Method.invoke(Method.java:498)
grails_1  |     at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
grails_1  |     at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
grails_1  |     at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
grails_1  |     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
grails_1  |     at groovy.lang.Closure.call(Closure.java:420)
grails_1  |     at groovy.lang.Closure.call(Closure.java:436)
grails_1  |     at org.grails.cli.gradle.GradleUtil$_withProjectConnection_closure1.doCall(GradleUtil.groovy:78)
grails_1  |     at org.grails.cli.gradle.GradleUtil$_withProjectConnection_closure1.call(GradleUtil.groovy)
grails_1  |     at grails.io.support.SystemOutErrCapturer.withNullOutput(SystemOutErrCapturer.groovy:64)
grails_1  |     at org.grails.cli.gradle.GradleUtil.withProjectConnection(GradleUtil.groovy:77)
grails_1  |     at org.grails.cli.gradle.GradleUtil.runBuildWithConsoleOutput(GradleUtil.groovy:92)
grails_1  |     at org.grails.cli.gradle.GradleInvoker.invokeMethod(GradleInvoker.groovy:50)
grails_1  |     at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:953)
grails_1  |     at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:930)
grails_1  |     at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:181)
grails_1  |     at org.grails.cli.gradle.GradleAsyncInvoker$_invokeMethod_closure2.doCall(GradleAsyncInvoker.groovy:57)
grails_1  |     at org.grails.cli.gradle.GradleAsyncInvoker$_invokeMethod_closure2.doCall(GradleAsyncInvoker.groovy)
grails_1  |     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
grails_1  |     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
grails_1  |     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
grails_1  |     at java.lang.reflect.Method.invoke(Method.java:498)
grails_1  |     at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
grails_1  |     at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
grails_1  |     at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
grails_1  |     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
grails_1  |     at groovy.lang.Closure.call(Closure.java:420)
grails_1  |     at groovy.lang.Closure.call(Closure.java:414)
grails_1  |     at groovy.lang.Closure.run(Closure.java:501)
grails_1  |     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
grails_1  |     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
grails_1  |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
grails_1  |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
grails_1  |     at java.lang.Thread.run(Thread.java:750)
grails_1  | Caused by: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':nodeSetup'.
grails_1  |     at org.gradle.initialization.DefaultExceptionAnalyser.transform(DefaultExceptionAnalyser.java:74)
grails_1  |     at org.gradle.initialization.MultipleBuildFailuresExceptionAnalyser.transform(MultipleBuildFailuresExceptionAnalyser.java:49)
grails_1  |     at org.gradle.initialization.MultipleBuildFailuresExceptionAnalyser.transform(MultipleBuildFailuresExceptionAnalyser.java:39)
grails_1  |     at org.gradle.initialization.StackTraceSanitizingExceptionAnalyser.transform(StackTraceSanitizingExceptionAnalyser.java:30)
grails_1  |     at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:152)
grails_1  |     at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:124)
grails_1  |     at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:77)
grails_1  |     at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:74)
grails_1  |     at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:154)
grails_1  |     at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:38)
grails_1  |     at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:96)
grails_1  |     at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:74)
grails_1  |     at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:55)
grails_1  |     at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
grails_1  |     at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
grails_1  |     at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
grails_1  |     at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.run(RunAsBuildOperationBuildActionRunner.java:50)
grails_1  |     at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
grails_1  |     at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
grails_1  |     at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
grails_1  |     at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
grails_1  |     at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
grails_1  |     at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45)
grails_1  |     at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
grails_1  |     at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47)
grails_1  |     at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:44)
grails_1  |     at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:79)
grails_1  |     at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:44)
grails_1  |     at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
grails_1  |     at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
grails_1  |     at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
grails_1  |     at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
grails_1  |     at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
grails_1  |     at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:62)
grails_1  |     at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:34)
grails_1  |     at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
grails_1  |     at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
grails_1  |     at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
grails_1  |     at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
grails_1  |     at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
grails_1  |     at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
grails_1  |     at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
grails_1  |     at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
grails_1  |     at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:46)
grails_1  |     at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
grails_1  |     at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
grails_1  |     at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
grails_1  |     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
grails_1  |     at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
grails_1  |     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
grails_1  |     at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
grails_1  |     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
grails_1  |     at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
grails_1  |     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
grails_1  |     at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
grails_1  |     at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
grails_1  |     at org.gradle.util.Swapper.swap(Swapper.java:38)
grails_1  |     at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
grails_1  |     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
grails_1  |     at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
grails_1  |     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
grails_1  |     at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
grails_1  |     at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
grails_1  |     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
grails_1  |     at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:81)
grails_1  |     at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
grails_1  |     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
grails_1  |     at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
grails_1  |     at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
grails_1  |     at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
grails_1  |     at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
grails_1  |     at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
grails_1  | Caused by: org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':nodeSetup'.
grails_1  |     at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
grails_1  |     at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
grails_1  |     at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
grails_1  |     at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:105)
grails_1  |     at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
grails_1  |     at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
grails_1  |     at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:79)
grails_1  |     at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
grails_1  |     at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
grails_1  |     at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
grails_1  |     at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
grails_1  |     at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
grails_1  |     at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
grails_1  |     at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
grails_1  |     at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
grails_1  |     at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
grails_1  |     at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
grails_1  |     at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
grails_1  |     at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
grails_1  |     at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
grails_1  |     at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
grails_1  |     at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
grails_1  |     at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
grails_1  |     at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
grails_1  |     at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
grails_1  |     at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
grails_1  |     at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
grails_1  |     at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
grails_1  |     at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
grails_1  |     at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
grails_1  |     at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
grails_1  |     ... 3 more
grails_1  | Caused by: org.gradle.api.UncheckedIOException: java.nio.file.FileSystemException: /app/.gradle/nodejs/node-v14.21.3-linux-x64/bin/npm: Operation not supported
grails_1  |     at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:57)
grails_1  |     at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
grails_1  |     at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)
grails_1  |     at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
grails_1  |     at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
grails_1  |     at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
grails_1  |     at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
grails_1  |     at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
grails_1  |     at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
grails_1  |     at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
grails_1  |     at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
grails_1  |     at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
grails_1  |     at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
grails_1  |     at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
grails_1  |     at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
grails_1  |     at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
grails_1  |     ... 33 more
grails_1  | Caused by: java.nio.file.FileSystemException: /app/.gradle/nodejs/node-v14.21.3-linux-x64/bin/npm: Operation not supported
grails_1  |     at com.moowork.gradle.node.task.SetupTask.unpackNodeArchive(SetupTask.groovy:139)
grails_1  |     at com.moowork.gradle.node.task.SetupTask.exec(SetupTask.groovy:80)
grails_1  |     at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
grails_1  |     ... 46 more
grails_1  | | Error Failed to start server
openboxes-docker_grails_1 exited with code 1
```

**Comment by ewaterman** [comment]
I'm going to close out this thread because it has become stale and we've since added more formal support for our Docker build. If any of the above issues persist on the latest release, please feel free to reopen
