### ISSUE TITLE
Purchase Order > HibernateException: Illegal attempt to associate a collection with two open sessions

### ISSUE THREAD

**Issue by jmiranda** [openboxes/openboxes#50]
Reported by Jesse Paulsen (thedanedan@gmail.com): 

**Stacktrace:**
```
Error 500: 
Servlet: 
URI: 
Exception Message: Illegal attempt to associate a collection with two open sessions 
Caused by: Exception thrown executing org.codehaus.groovy.grails.webflow.engine.builder.ClosureInvokingAction@25fa0c1c in state 'confirmOrderReceipt' of flow 'receiveOrderWorkflow/receiveOrder' -- action execution attributes were 'map[[empty]]' 
Class: ReceiveOrderWorkflowController 
At Line: [100] 
Code Snippet:
org.springframework.webflow.execution.ActionExecutionException: Exception thrown executing org.codehaus.groovy.grails.webflow.engine.builder.ClosureInvokingAction@25fa0c1c in state 'confirmOrderReceipt' of flow 'receiveOrderWorkflow/receiveOrder' -- action execution attributes were 'map[[empty]]'
	at grails.plugin.springcache.web.GrailsFragmentCachingFilter.doFilter(GrailsFragmentCachingFilter.groovy:66)
	at net.sf.ehcache.constructs.web.filter.Filter.doFilter(Filter.java:86)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.orm.hibernate3.HibernateSystemException: Illegal attempt to associate a collection with two open sessions; nested exception is org.hibernate.HibernateException: Illegal attempt to associate a collection with two open sessions
	at org.pih.warehouse.inventory.InventoryService.findOrCreateInventoryItem(InventoryService.groovy:2040)
	at org.pih.warehouse.inventory.InventoryService$$FastClassByCGLIB$$a7f866ff.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:149)
	at org.pih.warehouse.inventory.InventoryService$$EnhancerByCGLIB$$25941301.findOrCreateInventoryItem(<generated>)
	at org.pih.warehouse.inventory.InventoryService$findOrCreateInventoryItem.call(Unknown Source)
	at org.pih.warehouse.order.OrderService$_saveOrderShipment_closure3_closure10.doCall(OrderService.groovy:136)
	at $Proxy17.doInHibernate(Unknown Source)
	at org.pih.warehouse.order.OrderService$_saveOrderShipment_closure3.doCall(OrderService.groovy:135)
	at org.pih.warehouse.order.OrderService.saveOrderShipment(OrderService.groovy:126)
	at org.pih.warehouse.order.OrderService$$FastClassByCGLIB$$ca942d1b.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:149)
	at org.pih.warehouse.order.OrderService$$EnhancerByCGLIB$$65f8d35.saveOrderShipment(<generated>)
	at org.pih.warehouse.order.OrderService$saveOrderShipment.call(Unknown Source)
	at org.pih.warehouse.order.ReceiveOrderWorkflowController$_closure2_closure6_closure13.doCall(ReceiveOrderWorkflowController.groovy:100)
	... 3 more
Caused by: org.hibernate.HibernateException: Illegal attempt to associate a collection with two open sessions
	at $Proxy16.lock(Unknown Source)
	at $Proxy16.lock(Unknown Source)
	... 17 more
```

**Comment by jmiranda** [comment]
This occurs because we are using a different Hibernate session to find or create inventory items associated with the incoming stock. The inventory item cannot be associated with both sessions at the same time. It might be as easy as flushing the temporary session, but I need to investigate further.
