### ISSUE TITLE
Updating an existing openboxes installation

### ISSUE THREAD

**Issue by tgroff** [openboxes/openboxes#76]
Hello, I would like to update this file as I believe the latest commit will fix the problem we are experiencing:

https://github.com/openboxes/openboxes/blob/master/src/groovy/util/StringUtil.groovy

What is the recommended way to upgrade/update an existing installation? I see the "Upgrading" topic is in the [*coming soon* section of the wiki](https://github.com/openboxes/openboxes/wiki). 

I am of course concerned that there may be other commits and file changes that need to up updated along with this file. So I presume that updating this file by hand, or overwriting this file in my in my existing openboxes installation, wouldn't be a good idea? 

And, as I dig further, I see this file is not on my system as a plain-text file, which leads me to believe it's within the `openboxes.war` file? Thank you for your guidance as I am a PHP developer, and very much a n00b to Java applications.

Thank you!
--Tony

**Comment by jmiranda** [comment]
Yeah I assume that's the bug on the admin show settings page, right? Tomorrow I'll create a new release (WAR file) from the latest version of the code. From there the upgrade is usually pretty straightforward. 

1. Backup your database
2. Deploy the new WAR file to Tomcat (either through the tomcat manager app or by copying the WAR file to the tomcat webapps directory).

I'll update the Upgrade docs with more specific instructions.

**Comment by jmiranda** [comment]
You should be able to download the latest release (v0.7.3) from the Release page (https://github.com/openboxes/openboxes/releases/latest). 

Here are sample instructions for how to upgrade on Ubuntu:
$ sudo service tomcat7 stop
$ mysqldump -u root -p<password> openboxes > openboxes-20150818-1444.sql
$ sudo rm -rf /var/lib/tomcat7/webapps/openboxes*
$ sudo cp /path/to/openboxes.war /var/lib/tomcat7/webapps/
$ sudo service tomcat7 start

Or you could just use the Tomcat manager app 
![tomcat-manager](https://cloud.githubusercontent.com/assets/1162935/9340866/1256f9ea-45b8-11e5-8e1a-fcba2b08ee22.png)

Let me know if you have any other questions.

**Comment by jmiranda** [comment]
Closing the ticket. Let me know if you have any other questions.

**Comment by tgroff** [comment]
Hello, thank you for the very detailed information. I followed the procedures, but the application would not start. So I reverted back to v0.7.0. In the error logs it looks like it sends you an email, but the errors are pasted below here in case you do not receive the email. 

Thank you again for your help and guidance.

```
2015-08-20 00:55:34,385 [http-bio-8080-exec-3] INFO  cfg.Environment  - Hibernate 3.3.1.GA
2015-08-20 00:55:34,391 [http-bio-8080-exec-3] INFO  cfg.Environment  - hibernate.properties not found
2015-08-20 00:55:34,396 [http-bio-8080-exec-3] INFO  cfg.Environment  - Bytecode provider name : javassist
2015-08-20 00:55:34,420 [http-bio-8080-exec-3] INFO  cfg.Environment  - using JDK 1.4 java.sql.Timestamp handling
2015-08-20 00:55:36,393 [http-bio-8080-exec-3] INFO  support.DefaultListableBeanFactory  - Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@45d336db: defining beans [grailsApplication,pluginManager,grailsConfigurator,grailsResourceLoader,grailsResourceHolder,characterEncodingFilter]; root of factory hierarchy
2015-08-20 00:55:36,397 [http-bio-8080-exec-3] ERROR context.ContextLoader  - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pluginManager' defined in ServletContext resource [/WEB-INF/applicationContext.xml]: Invocation of init method failed; nested exception is java.lang.RuntimeException: Unable to locate constructor with Class parameter for class org.codehaus.groovy.grails.commons.DefaultGrailsServiceClass
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unable to locate constructor with Class parameter for class org.codehaus.groovy.grails.commons.DefaultGrailsServiceClass
        ... 3 more
Caused by: java.lang.reflect.InvocationTargetException
        ... 3 more
Caused by: java.lang.NoClassDefFoundError: org/krysalis/barcode4j/BarcodeGenerator
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
        at java.lang.Class.getDeclaredMethods(Class.java:1860)
        ... 3 more
Caused by: java.lang.ClassNotFoundException: org.krysalis.barcode4j.BarcodeGenerator
        ... 6 more
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Sun Microsystems, Inc]
DEBUG SMTP: useEhlo true, useAuth false
DEBUG SMTP: trying to connect to host "localhost", port 25, isSSL false
220 openboxes ESMTP Postfix (Ubuntu)
DEBUG SMTP: connected to host "localhost", port: 25

EHLO openboxes
250-openboxes
250-PIPELINING
250-SIZE 10240000
250-VRFY
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN

<-- SNIPPED --->

Date: Aug-20-2015 00:55:36.397
Thread: [http-bio-8080-exec-3]
Username:
Location:
Locale:
IP address:  http://whatismyipaddress.com/ip/
Request URI:
Request URL:
Query string:
Server:
Clickstream:

Stacktrace:
Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pluginManager' defined in ServletContext resource [/WEB-INF/applicationContext.xml]: Invocation of init method failed; nested exception is java.lang.RuntimeException: Unable to locate constructor with Class parameter for class org.codehaus.groovy.grails.commons.DefaultGrailsServiceClass
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unable to locate constructor with Class parameter for class org.codehaus.groovy.grails.commons.DefaultGrailsServiceClass
        ... 3 more
Caused by: java.lang.reflect.InvocationTargetException
        ... 3 more
Caused by: java.lang.NoClassDefFoundError: org/krysalis/barcode4j/BarcodeGenerator
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
        at java.lang.Class.getDeclaredMethods(Class.java:1860)
        ... 3 more
Caused by: java.lang.ClassNotFoundException: org.krysalis.barcode4j.BarcodeGenerator
        ... 6 more

------=_Part_0_1284892243.1440046536409--
.
250 2.0.0 Ok: queued as 7CEF0120389
QUIT
221 2.0.0 Bye
Aug 20, 2015 12:55:36 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
Aug 20, 2015 12:55:36 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/openboxes] startup failed due to previous errors
Aug 20, 2015 12:55:36 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/openboxes] appears to have started a thread named [AsyncAppender-Dispatcher-Thread-4] but has failed to stop it. This is very likely to create a memory leak.
```

**Comment by jmiranda** [comment]
Ok, I'll take a look.

**Comment by jmiranda** [comment]
For some reason, the v0.7.3 WAR file that I built locally did not contain the barcode4j JAR. I just downloaded the WAR file that was built using Bamboo (http://bamboo.pih-emr.org:8085/browse/OPENBOXES-OSSD-33/artifact), made sure it had the barcode4j JAR and created a new v0.7.3 release on GitHub. Could you download that WAR file (https://github.com/openboxes/openboxes/releases/tag/v0.7.3) and try again?

**Comment by tgroff** [comment]
Hello, the latest v0.7.3 deployed properly, all is well. This has also fixed - https://github.com/openboxes/openboxes/issues/72

Thank you!
