### ISSUE TITLE
Bug while creating a stock requisition

### ISSUE THREAD

**Issue by jmiranda** [openboxes/openboxes#896]
```Error 500: 
Servlet: 
URI: 
Exception Message: No signature of method: static java.lang.Boolean.parseBoolean() is applicable for argument types: (null) values: [null] Possible solutions: parseBoolean(java.lang.String), asBoolean(), asBoolean() 
Caused by: Error processing GroovyPageView: Error executing tag <g:form>: Error executing tag <g:selectRequisitionTemplate>: groovy.lang.MissingMethodException: No signature of method: static java.lang.Boolean.parseBoolean() is applicable for argument types: (null) values: [null] Possible solutions: parseBoolean(java.lang.String), asBoolean(), asBoolean() at /WEB-INF/grails-app/views/requisition/chooseTemplate.gsp:75 at /WEB-INF/grails-app/views/requisition/chooseTemplate.gsp:81 
Class: SelectTagLib 
At Line: [124] 
Code Snippet:
```

**Comment by jmiranda** [comment]
Another report of this bug from chat:
(11:32:37) *** Mr Administrator joined the chat *** 
(11:32:37) Mr Administrator: Seems this demo instance is real buggy. Keep getting errors. Just now cannot create a requisition. Error 500: 
{code}
Exception Message: No signature of method: static java.lang.Boolean.parseBoolean() is applicable for argument types: (null) values: [null] Possible solutions: parseBoolean(java.lang.String), asBoolean(), asBoolean() 
Caused by: Error processing GroovyPageView: Error executing tag <g:form>: Error executing tag <g:selectRequisitionTemplate>: groovy.lang.MissingMethodException: No signature of method: static java.lang.Boolean.parseBoolean() is applicable for argument types: (null) values: [null] Possible solutions: parseBoolean(java.lang.String), asBoolean(), asBoolean() at /WEB-INF/grails-app/views/requisition/chooseTemplate.gsp:75 at /WEB-INF/grails-app/views/requisition/chooseTemplate.gsp:81 
Class: SelectTagLib 
At Line: [124] 
{code}

**Comment by jmiranda** [comment]
Just realized the stacktrace is actually useful in this case. Usually when the error occurs within a GSP it only shows the line number in the compiled GSP (which isn't all that useful). But since the error occurs inside the RequisitionService called by SelectTagLib, it's more clear where the issue occurs. So this should be easy to fix.
{code}
org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag <g:form>: Error executing tag <g:selectRequisitionTemplate>: groovy.lang.MissingMethodException: No signature of method: static java.lang.Boolean.parseBoolean() is applicable for argument types: (null) values: [null]
Possible solutions: parseBoolean(java.lang.String), asBoolean(), asBoolean() at /WEB-INF/grails-app/views/requisition/chooseTemplate.gsp:75 at /WEB-INF/grails-app/views/requisition/chooseTemplate.gsp:81

	at grails.plugin.springcache.web.GrailsFragmentCachingFilter.doFilter(GrailsFragmentCachingFilter.groovy:66)

	at net.sf.ehcache.constructs.web.filter.Filter.doFilter(Filter.java:86)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)

	at java.lang.Thread.run(Thread.java:748)

Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:form>: Error executing tag <g:selectRequisitionTemplate>: groovy.lang.MissingMethodException: No signature of method: static java.lang.Boolean.parseBoolean() is applicable for argument types: (null) values: [null]
Possible solutions: parseBoolean(java.lang.String), asBoolean(), asBoolean() at /WEB-INF/grails-app/views/requisition/chooseTemplate.gsp:75 at /WEB-INF/grails-app/views/requisition/chooseTemplate.gsp:81

	at gsp_openboxes_requisitionchooseTemplate_gsp$_run_closure2.doCall(gsp_openboxes_requisitionchooseTemplate_gsp.groovy:119)

	at gsp_openboxes_requisitionchooseTemplate_gsp$_run_closure2.doCall(gsp_openboxes_requisitionchooseTemplate_gsp.groovy)

	at gsp_openboxes_requisitionchooseTemplate_gsp.run(gsp_openboxes_requisitionchooseTemplate_gsp.groovy:122)

	... 5 more

Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:selectRequisitionTemplate>: groovy.lang.MissingMethodException: No signature of method: static java.lang.Boolean.parseBoolean() is applicable for argument types: (null) values: [null]
Possible solutions: parseBoolean(java.lang.String), asBoolean(), asBoolean() at /WEB-INF/grails-app/views/requisition/chooseTemplate.gsp:75

	at gsp_openboxes_requisitionchooseTemplate_gsp$_run_closure2_closure7.doCall(gsp_openboxes_requisitionchooseTemplate_gsp.groovy:116)

	at gsp_openboxes_requisitionchooseTemplate_gsp$_run_closure2_closure7.doCall(gsp_openboxes_requisitionchooseTemplate_gsp.groovy)

	... 8 more

Caused by: org.codehaus.groovy.runtime.InvokerInvocationException: groovy.lang.MissingMethodException: No signature of method: static java.lang.Boolean.parseBoolean() is applicable for argument types: (null) values: [null]
Possible solutions: parseBoolean(java.lang.String), asBoolean(), asBoolean()

	... 10 more

Caused by: groovy.lang.MissingMethodException: No signature of method: static java.lang.Boolean.parseBoolean() is applicable for argument types: (null) values: [null]
Possible solutions: parseBoolean(java.lang.String), asBoolean(), asBoolean()

	at org.pih.warehouse.requisition.RequisitionService.getRequisitions(RequisitionService.groovy:212)

	at org.pih.warehouse.requisition.RequisitionService$getRequisitions.callCurrent(Unknown Source)

	at org.pih.warehouse.requisition.RequisitionService.getAllRequisitionTemplates(RequisitionService.groovy:174)

	at org.pih.warehouse.requisition.RequisitionService$$FastClassByCGLIB$$56b29ff.invoke(<generated>)

	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:149)

	at org.pih.warehouse.requisition.RequisitionService$$EnhancerByCGLIB$$13f81412.getAllRequisitionTemplates(<generated>)

	at org.pih.warehouse.requisition.RequisitionService$getAllRequisitionTemplates.call(Unknown Source)

	at org.pih.warehouse.SelectTagLib$_closure10.doCall(SelectTagLib.groovy:124)

	... 10 more
{code}

**Comment by jmiranda** [comment]
Looks like a server restart cleared the error. Still planning to investigate to see what's causing it.

**Comment by ewaterman** [comment]
closing this out since this is a really old issue and we no longer have a `parseBoolean` call in RequisitionService (where the exception was being thrown). The logic has since been refactored.
