### ISSUE TITLE
NullPointerException while receiving order

### ISSUE THREAD

**Issue by jmiranda** [openboxes/openboxes#988]
```
Date: Apr-15-2019 10:09:09.825
Request URI: /openboxes/grails/receiveOrderWorkflow/receiveOrder.dispatch
Request URL: http://192.168.1.195:8080/openboxes/grails/receiveOrderWorkflow/receiveOrder.dispatch
Query string: execution=e1s3
Server: http://localhost:8080/openboxes

Stacktrace: 
Exception occurred when processing request: [POST] /openboxes/receiveOrderWorkflow/receiveOrder
Stacktrace follows:
org.springframework.webflow.execution.ActionExecutionException: Exception thrown executing org.codehaus.groovy.grails.webflow.engine.builder.ClosureInvokingAction@4bdd446a in state 'confirmOrderReceipt' of flow 'receiveOrderWorkflow/receiveOrder' -- action execution attributes were 'map[[empty]]'
        at grails.plugin.springcache.web.GrailsFragmentCachingFilter.doFilter(GrailsFragmentCachingFilter.groovy:66)
        at net.sf.ehcache.constructs.web.filter.Filter.doFilter(Filter.java:86)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: Cannot get property 'actualDeliveryDate' on null object
        at org.pih.warehouse.shipping.ShipmentService.receiveShipment(ShipmentService.groovy:1477)
        at org.pih.warehouse.shipping.ShipmentService$$FastClassByCGLIB$$7a8c772f.invoke(<generated>)
        at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:149)
        at org.pih.warehouse.shipping.ShipmentService$$EnhancerByCGLIB$$55bb5242.receiveShipment(<generated>)
        at org.pih.warehouse.shipping.ShipmentService$receiveShipment.call(Unknown Source)
        at org.pih.warehouse.order.OrderService.saveOrderShipment(OrderService.groovy:195)
        at org.pih.warehouse.order.OrderService$$FastClassByCGLIB$$ca942d1b.invoke(<generated>)
        at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:149)
        at org.pih.warehouse.order.OrderService$$EnhancerByCGLIB$$33a54e66.saveOrderShipment(<generated>)
        at org.pih.warehouse.order.OrderService$saveOrderShipment.call(Unknown Source)
        at org.pih.warehouse.order.ReceiveOrderWorkflowController$_closure2_closure6_closure13.doCall(ReceiveOrderWorkflowController.groovy:100)
        ... 5 more
```

**Comment by jmiranda** [comment]
Unable to reproduce with version 0.8.6. Waiting for feedback from user.
